const services = [
    // ==================== সরকারি সেবা ====================
    { cat: "সরকারি সেবা", icon: "fa-building-columns", t: "জাতীয় পোর্টাল", d: "সব সরকারি সেবা", url: "https://bangladesh.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-passport", t: "ই-পাসপোর্ট", d: "আবেদন ও স্ট্যাটাস", url: "https://epassport.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-id-card", t: "NID সেবা", d: "স্মার্ট আইডি, সংশোধন", url: "https://services.nidw.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-baby", t: "জন্ম নিবন্ধন", d: "অনলাইন নিবন্ধন", url: "https://bdris.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-file-invoice", t: "ই-টিন (NBR)", d: "টিন সার্টিফিকেট", url: "https://etaxnbr.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-shield", t: "পুলিশ ক্লিয়ারেন্স", d: "অনলাইন আবেদন", url: "https://pcc.police.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-car", t: "ড্রাইভিং লাইসেন্স", d: "BRTA সেবা", url: "https://bsp.brta.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-ballot", t: "ভোটার তথ্য", d: "ভোটার তালিকা", url: "https://ecs.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-tree", t: "ভূমি পোর্টাল", d: "নামজারি, খাজনা", url: "https://land.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-gavel", t: "আইন ও আদালত", d: "ই-জুডিশিয়ারি", url: "https://services.judiciary.org.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-hospital", t: "স্বাস্থ্য সেবা", d: "DGHS", url: "https://dghs.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-graduation-cap", t: "শিক্ষা বোর্ড", d: "ফলাফল", url: "https://eboardresults.com", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-phone", t: "জরুরি সেবা", d: "৯৯৯, অ্যাম্বুলেন্স", url: "https://999.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-building", t: "RJSC কোম্পানি", d: "কোম্পানি রেজিস্ট্রি", url: "https://www.roc.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-store", t: "ট্রেড লাইসেন্স", d: "ব্যবসা লাইসেন্স", url: "https://dhaka.gov.bd/site/view/trade_license", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-hand-holding-dollar", t: "SME সেবা", d: "ক্ষুদ্র ব্যবসা", url: "https://www.sme.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-file-contract", t: "ফার্ম রেজিস্ট্রি", d: "ব্যবসা নিবন্ধন", url: "https://firm.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-user-tie", t: "BPSC চাকরি", d: "সরকারি চাকরি", url: "https://bpsc.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-users", t: "বাংলাদেশ কর্মকমিশন", d: "চাকরির বিজ্ঞপ্তি", url: "https://psc.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-futbol", t: "ক্রীড়া মন্ত্রণালয়", d: "স্পোর্টস নিউজ", url: "https://youthsports.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-newspaper", t: "প্রধানমন্ত্রীর কার্যালয়", d: "সরকারি সংবাদ", url: "https://www.pmo.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-broadcast", t: "বিটিভি নিউজ", d: "সরকারি টিভি", url: "https://btv.gov.bd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-file-pdf", t: "PDF ডাউনলোড", d: "সকল সরকারি ফর্ম", url: "https://www.mof.gov.bd/pdf", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-file-pdf", t: "NID ফর্ম PDF", d: "NID সংশোধন ফর্ম", url: "https://services.nidw.gov.bd/form", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-file-pdf", t: "পাসপোর্ট ফর্ম PDF", d: "আবেদন ফর্ম", url: "https://epassport.gov.bd/forms", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-file-pdf", t: "টিন ফর্ম PDF", d: "NBR ফর্ম", url: "https://etaxnbr.gov.bd/forms", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-image", t: "বাংলাদেশের ছবি", d: "দর্শনীয় স্থান", url: "https://tourism.gov.bd/gallery", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-image", t: "ম্যাপ ও চিত্র", d: "জমির ম্যাপ", url: "https://land.gov.bd/map", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-image", t: "তথ্য চিত্র", d: "Infographics", url: "https://a2i.gov.bd/infographic", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-video", t: "সরকারি ভিডিও", d: "প্রচার ও শিক্ষা", url: "https://www.youtube.com/@bangladeshgov", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-video", t: "টিউটোরিয়াল", d: "সেবা ব্যবহারের ভিডিও", url: "https://www.youtube.com/@a2ibd", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-video", t: "সংসদ ভিডিও", d: "সেশন রেকর্ডিং", url: "https://www.parliament.gov.bd/videos", type: "govt" },
    { cat: "সরকারি সেবা", icon: "fa-code", t: "বাংলাদেশ ওপেন সোর্স", d: "GitHub রিপোজিটরি", url: "https://github.com/bangladesh", type: "other" },
    { cat: "সরকারি সেবা", icon: "fa-code", t: "ডিজিটাল বাংলাদেশ কোড", d: "সরকারি অ্যাপ কোড", url: "https://github.com/a2i", type: "other" },
    { cat: "সরকারি সেবা", icon: "fa-code", t: "API ডকুমেন্টেশন", d: "সরকারি API", url: "https://api.gov.bd", type: "other" },
    
    // ==================== শিক্ষা প্রতিষ্ঠান ====================
    { cat: "শিক্ষা", icon: "fa-school", t: "BUET", d: "প্রকৌশল বিশ্ববিদ্যালয়", url: "https://www.buet.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "DU", d: "ঢাকা বিশ্ববিদ্যালয়", url: "https://www.du.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "JU", d: "জাহাঙ্গীরনগর বিশ্ববিদ্যালয়", url: "https://juniv.edu", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "CU", d: "চট্টগ্রাম বিশ্ববিদ্যালয়", url: "https://cu.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "RU", d: "রাজশাহী বিশ্ববিদ্যালয়", url: "https://www.ru.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "KU", d: "খুলনা বিশ্ববিদ্যালয়", url: "https://ku.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "SUST", d: "শাহজালাল বিজ্ঞান ও প্রযুক্তি", url: "https://www.sust.edu", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "BAU", d: "বাংলাদেশ কৃষি বিশ্ববিদ্যালয়", url: "https://www.bau.edu.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "BSMMU", d: "মেডিকেল বিশ্ববিদ্যালয়", url: "https://bsmmu.edu.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "NSU", d: "নর্থ সাউথ বিশ্ববিদ্যালয়", url: "https://www.northsouth.edu", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "BRAC", d: "ব্র্যাক বিশ্ববিদ্যালয়", url: "https://www.bracu.ac.bd", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "AIUB", d: "আমেরিকান ইন্টারন্যাশনাল", url: "https://www.aiub.edu", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "EWU", d: "ইস্ট ওয়েস্ট বিশ্ববিদ্যালয়", url: "https://www.ewubd.edu", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "IUT", d: "ইসলামিক ইউনিভার্সিটি অফ টেকনোলজি", url: "https://www.iutoic-dhaka.edu", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "DUET", d: "প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়", url: "https://www.duet.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "KUET", d: "খুলনা প্রকৌশল বিশ্ববিদ্যালয়", url: "https://www.kuet.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "RUET", d: "রাজশাহী প্রকৌশল বিশ্ববিদ্যালয়", url: "https://www.ruet.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "CUET", d: "চট্টগ্রাম প্রকৌশল বিশ্ববিদ্যালয়", url: "https://www.cuet.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "MBSTU", d: "মাওলানা ভাসানী বিজ্ঞান ও প্রযুক্তি", url: "https://mbstu.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "PUST", d: "পাবনা বিজ্ঞান ও প্রযুক্তি", url: "https://www.pust.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "NSTU", d: "নোয়াখালী বিজ্ঞান ও প্রযুক্তি", url: "https://nstu.edu.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "JKKNIU", d: "জাতীয় কবি কাজী নজরুল ইসলাম", url: "https://jkkniu.edu.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "IUB", d: "ইন্ডিপেন্ডেন্ট ইউনিভার্সিটি", url: "https://www.iub.edu.bd", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "UIU", d: "ইউনাইটেড ইন্টারন্যাশনাল", url: "https://www.uiu.ac.bd", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "Daffodil", d: "ড্যাফোডিল ইন্টারন্যাশনাল", url: "https://daffodilvarsity.edu.bd", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "AUST", d: "আহসানউল্লাহ বিজ্ঞান ও প্রযুক্তি", url: "https://www.aust.edu", type: "private" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "MIST", d: "মিলিটারি ইনস্টিটিউট অফ সায়েন্স", url: "https://mist.ac.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "BUP", d: "বাংলাদেশ ইউনিভার্সিটি অফ প্রফেশনালস", url: "https://bup.edu.bd", type: "govt" },
    { cat: "শিক্ষা", icon: "fa-building-columns", t: "JNU", d: "জগন্নাথ বিশ্ববিদ্যালয়", url: "https://jnu.ac.bd", type: "govt" },

    // ==================== বেসরকারি সেবা ====================
    { cat: "বেসরকারি সেবা", icon: "fa-mobile-screen", t: "bKash", d: "মোবাইল ব্যাংকিং", url: "https://www.bkash.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-wallet", t: "Nagad", d: "ডিজিটাল ওয়ালেট", url: "https://nagad.com.bd", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-rocket", t: "Rocket", d: "DBBL মোবাইল", url: "https://www.dutchbanglabank.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-store", t: "ShopUp", d: "অনলাইন ব্যবসা", url: "https://shopup.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-truck", t: "FoodPanda", d: "খাবার ডেলিভারি", url: "https://www.foodpanda.com.bd", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-truck", t: "Pathao", d: "রাইড শেয়ারিং", url: "https://pathao.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-car", t: "Uber Bangladesh", d: "রাইড শেয়ারিং", url: "https://www.uber.com/bd", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-bag-shopping", t: "Daraz", d: "অনলাইন শপিং", url: "https://www.daraz.com.bd", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-bag-shopping", t: "Chaldal", d: "অনলাইন গ্রোসারি", url: "https://chaldal.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-plane", t: "বিমান বাংলাদেশ", d: "ফ্লাইট বুকিং", url: "https://www.biman-airlines.com", type: "govt" },
    { cat: "বেসরকারি সেবা", icon: "fa-plane", t: "US-Bangla Airlines", d: "ফ্লাইট বুকিং", url: "https://usbair.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-train", t: "রেলওয়ে টিকেট", d: "ট্রেনের টিকেট", url: "https://eticket.railway.gov.bd", type: "govt" },
    { cat: "বেসরকারি সেবা", icon: "fa-bus", t: "বাস টিকেট", d: "Shohoz বাস", url: "https://www.shohoz.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-hotel", t: "হোটেল বুকিং", d: "বাংলাদেশ হোটেল", url: "https://www.booking.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-film", t: "Bioscope", d: "সিনেমা স্ট্রিমিং", url: "https://bioscopelive.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-music", t: "GP Music", d: "গান শোনা", url: "https://gpmusic.co", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-cloud", t: "Google Drive", d: "ক্লাউড স্টোরেজ", url: "https://drive.google.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-envelope", t: "Gmail", d: "ইমেইল", url: "https://mail.google.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-video", t: "YouTube", d: "ভিডিও স্ট্রিমিং", url: "https://www.youtube.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-users", t: "Facebook", d: "সামাজিক মাধ্যম", url: "https://www.facebook.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-comment", t: "Messenger", d: "মেসেজিং অ্যাপ", url: "https://www.messenger.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-camera", t: "Instagram", d: "ছবি শেয়ারিং", url: "https://www.instagram.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-briefcase", t: "LinkedIn", d: "পেশাদার নেটওয়ার্ক", url: "https://www.linkedin.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-comments", t: "WhatsApp", d: "মেসেজিং অ্যাপ", url: "https://www.whatsapp.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-mobile-screen", t: "Telegram", d: "মেসেজিং অ্যাপ", url: "https://telegram.org", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-cloud-sun", t: "Weather.com", d: "আবহাওয়ার খবর", url: "https://weather.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-map", t: "Google Maps", d: "ম্যাপ ও নেভিগেশন", url: "https://maps.google.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-code", t: "GitHub", d: "কোড হোস্টিং", url: "https://github.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-code", t: "Stack Overflow", d: "প্রোগ্রামিং প্রশ্ন", url: "https://stackoverflow.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-palette", t: "Canva", d: "গ্রাফিক ডিজাইন", url: "https://www.canva.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-file-pdf", t: "SmallPDF", d: "PDF টুলস", url: "https://smallpdf.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-file-word", t: "Google Docs", d: "অনলাইন ডকুমেন্ট", url: "https://docs.google.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-file-excel", t: "Google Sheets", d: "অনলাইন স্প্রেডশিট", url: "https://sheets.google.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-image", t: "Imgur", d: "ছবি আপলোড", url: "https://imgur.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-folder", t: "Dropbox", d: "ক্লাউড স্টোরেজ", url: "https://www.dropbox.com", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-calendar", t: "Zoom", d: "ভিডিও মিটিং", url: "https://zoom.us", type: "private" },
    { cat: "বেসরকারি সেবা", icon: "fa-calendar", t: "Google Meet", d: "ভিডিও মিটিং", url: "https://meet.google.com", type: "private" },

    // ==================== ব্যাংক ও আর্থিক সেবা ====================
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Sonali Bank", d: "রাষ্ট্রায়ত্ত ব্যাংক", url: "https://www.sonalibank.com.bd", type: "govt" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Janata Bank", d: "রাষ্ট্রায়ত্ত ব্যাংক", url: "https://www.janatabank-bd.com", type: "govt" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Agrani Bank", d: "রাষ্ট্রায়ত্ত ব্যাংক", url: "https://www.agranibank.org", type: "govt" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Rupali Bank", d: "রাষ্ট্রায়ত্ত ব্যাংক", url: "https://www.rupalibank.org", type: "govt" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Bangladesh Bank", d: "কেন্দ্রীয় ব্যাংক", url: "https://www.bb.org.bd", type: "govt" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "DBBL", d: "ডাচ-বাংলা ব্যাংক", url: "https://www.dutchbanglabank.com", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "BRAC Bank", d: "ব্র্যাক ব্যাংক", url: "https://www.bracbank.com", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "City Bank", d: "সিটি ব্যাংক", url: "https://www.thecitybank.com", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Islami Bank", d: "ইসলামী ব্যাংক", url: "https://www.islamibankbd.com", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "Prime Bank", d: "প্রাইম ব্যাংক", url: "https://www.primebank.com.bd", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "UCB", d: "ইউনাইটেড কমার্শিয়াল ব্যাংক", url: "https://www.ucb.com.bd", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "E BL", d: "ইস্টার্ন ব্যাংক", url: "https://www.ebl.com.bd", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "MTB", d: "মিউচুয়াল ট্রাস্ট ব্যাংক", url: "https://www.mutualtrustbank.com", type: "private" },
    { cat: "ব্যাংকিং", icon: "fa-building-columns", t: "IFIC Bank", d: "ইন্টারন্যাশনাল ফাইন্যান্স", url: "https://www.ificbank.com.bd", type: "private" },

    // ==================== সংবাদ মাধ্যম ====================
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Prothom Alo", d: "প্রথম আলো", url: "https://www.prothomalo.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Daily Star", d: "ইংরেজি সংবাদ", url: "https://www.thedailystar.net", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "bdnews24.com", d: "অনলাইন নিউজ", url: "https://www.bdnews24.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Jugantor", d: "যুগান্তর", url: "https://www.jugantor.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Ittefaq", d: "ইত্তেফাক", url: "https://www.ittefaq.com.bd", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Kaler Kantho", d: "কালের কণ্ঠ", url: "https://www.kalerkantho.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Bangladesh Pratidin", d: "বাংলাদেশ প্রতিদিন", url: "https://www.bd-pratidin.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Samakal", d: "সমকাল", url: "https://www.samakal.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Manab Zamin", d: "মানবজমিন", url: "https://www.manabzamin.net", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "BBC Bangla", d: "বিবিসি বাংলা", url: "https://www.bbc.com/bengali", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "DW Bangla", d: "ডয়চে ভেলে", url: "https://www.dw.com/bn", type: "private" },
    { cat: "সংবাদ", icon: "fa-newspaper", t: "Voice of America", d: "ভিওএ বাংলা", url: "https://www.voabangla.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "Somoy TV", d: "সময় টিভি", url: "https://www.somoynews.tv", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "Channel 24", d: "চ্যানেল টোয়েন্টিফোর", url: "https://www.channel24bd.tv", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "Jamuna TV", d: "যমুনা টিভি", url: "https://www.jamuna.tv", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "Independent TV", d: "ইন্ডিপেন্ডেন্ট টিভি", url: "https://www.independent24.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "ATN Bangla", d: "এটিএন বাংলা", url: "https://www.atnbangla.tv", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "NTV", d: "এনটিভি", url: "https://www.ntvbd.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "RTV", d: "আরটিভি", url: "https://www.rtvonline.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "Ekushey TV", d: "একুশে টিভি", url: "https://www.ekushey-tv.com", type: "private" },
    { cat: "সংবাদ", icon: "fa-tv", t: "DBC News", d: "ডিবিসি নিউজ", url: "https://www.dbcnews.tv", type: "private" },

    // ==================== স্বাস্থ্য ও চিকিৎসা ====================
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "Apollo Hospitals", d: "বেসরকারি হাসপাতাল", url: "https://www.apollodhaka.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "Square Hospital", d: "বেসরকারি হাসপাতাল", url: "https://www.squarehospital.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "United Hospital", d: "বেসরকারি হাসপাতাল", url: "https://www.uhlbd.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "Labaid", d: "ল্যাবএইড হাসপাতাল", url: "https://labaidgroup.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "Ibn Sina", d: "ইবনে সিনা হাসপাতাল", url: "https://www.ibnsinatrust.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "Birdem", d: "বারডেম হাসপাতাল", url: "https://www.birdem.org", type: "govt" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "DMCH", d: "ঢাকা মেডিকেল কলেজ", url: "https://www.dmch.org.bd", type: "govt" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "BSMMU", d: "বঙ্গবন্ধু মেডিকেল", url: "https://bsmmu.edu.bd", type: "govt" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "CMH", d: "সম্মিলিত সামরিক হাসপাতাল", url: "https://www.cmh.gov.bd", type: "govt" },
    { cat: "স্বাস্থ্য", icon: "fa-hospital", t: "NICVD", d: "হৃদরোগ হাসপাতাল", url: "https://www.nicvd.gov.bd", type: "govt" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "Praava Health", d: "ডিজিটাল হেলথ", url: "https://www.praavahealth.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "DocTime", d: "অনলাইন ডাক্তার", url: "https://www.doctime.com.bd", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "Olwel", d: "ডিজিটাল স্বাস্থ্য", url: "https://olwel.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "Doctorola", d: "ডাক্তার বুকিং", url: "https://doctorola.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "Jeeon", d: "গ্রামীণ স্বাস্থ্য", url: "https://www.jeeon.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "Maya", d: "মায়া হেলথ", url: "https://www.maya.com.bd", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "Arogga", d: "অনলাইন ফার্মেসি", url: "https://www.arogga.com", type: "private" },
    { cat: "স্বাস্থ্য", icon: "fa-stethoscope", t: "MedEasy", d: "ঔষধ ডেলিভারি", url: "https://medeasy.com.bd", type: "private" },

    // ==================== রেসিপি ও খাবার ====================
    { cat: "রেসিপি", icon: "fa-utensils", t: "Bangladeshi Food", d: "বাংলাদেশী রেসিপি", url: "https://www.bangladeshifood.com", type: "private" },
    { cat: "রেসিপি", icon: "fa-utensils", t: "Nadia's Kitchen", d: "রান্নার টিপস", url: "https://www.nadiaskitchen.com", type: "private" },
    { cat: "রেসিপি", icon: "fa-utensils", t: "Cookpad BD", d: "কুকপ্যাড বাংলাদেশ", url: "https://cookpad.com/bd", type: "private" },
    { cat: "রেসিপি", icon: "fa-utensils", t: "Food Fusion BD", d: "ফুড ফিউশন", url: "https://www.youtube.com/@FoodFusionBangladesh", type: "private" },
    { cat: "রেসিপি", icon: "fa-utensils", t: "Bong Eats", d: "বাংলা খাবার", url: "https://bongeats.com", type: "private" },
    { cat: "রেসিপি", icon: "fa-utensils", t: "Deshi Food", d: "দেশি খাবার", url: "https://www.deshifood.com", type: "private" },

    // ==================== আইটি ও টেকনোলজি ====================
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "TechLand BD", d: "টেকনোলজি নিউজ", url: "https://www.techlandbd.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "Pi Labs BD", d: "টেক নিউজ", url: "https://www.pilabsbd.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "TechGiant", d: "গ্যাজেট রিভিউ", url: "https://www.techgiant.net", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "Gadget & Gear", d: "গ্যাজেট শপ", url: "https://www.gadgetandgear.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "Star Tech", d: "কম্পিউটার শপ", url: "https://www.startech.com.bd", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "Ryans Computers", d: "কম্পিউটার শপ", url: "https://www.ryanscomputers.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-laptop", t: "Global Brand", d: "ল্যাপটপ শপ", url: "https://www.globalbrand.com.bd", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-code", t: "W3Schools", d: "কোডিং শেখা", url: "https://www.w3schools.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-code", t: "FreeCodeCamp", d: "ফ্রি কোডিং", url: "https://www.freecodecamp.org", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-code", t: "Codecademy", d: "কোডিং শেখা", url: "https://www.codecademy.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-code", t: "Udemy", d: "অনলাইন কোর্স", url: "https://www.udemy.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-code", t: "Coursera", d: "অনলাইন কোর্স", url: "https://www.coursera.org", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-code", t: "edX", d: "অনলাইন কোর্স", url: "https://www.edx.org", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "DigitalOcean", d: "ক্লাউড হোস্টিং", url: "https://www.digitalocean.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "Vercel", d: "ওয়েব হোস্টিং", url: "https://vercel.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "Netlify", d: "ওয়েব হোস্টিং", url: "https://www.netlify.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "Heroku", d: "অ্যাপ হোস্টিং", url: "https://www.heroku.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "Firebase", d: "Google Firebase", url: "https://firebase.google.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "AWS", d: "Amazon Web Services", url: "https://aws.amazon.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "Microsoft Azure", d: "ক্লাউড সেবা", url: "https://azure.microsoft.com", type: "private" },
    { cat: "টেকনোলজি", icon: "fa-cloud", t: "Google Cloud", d: "ক্লাউড সেবা", url: "https://cloud.google.com", type: "private" },

    // ==================== চাকরি ====================
    { cat: "চাকরি", icon: "fa-briefcase", t: "BDJobs", d: "প্রধান চাকরির সাইট", url: "https://www.bdjobs.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Prothom Alo Jobs", d: "চাকরির বিজ্ঞাপন", url: "https://jobs.prothomalo.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "CareerJet", d: "চাকরির সার্চ ইঞ্জিন", url: "https://www.careerjet.com.bd", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "JagoJobs", d: "চাকরির সাইট", url: "https://www.jagojobs.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "LinkedIn Jobs", d: "প্রফেশনাল জব", url: "https://www.linkedin.com/jobs", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Everjobs", d: "চাকরির সাইট", url: "https://www.everjobs.com.bd", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Bdjobs Today", d: "চাকরির আপডেট", url: "https://www.bdjobstoday.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Niyog Khoje", d: "সরকারি চাকরি", url: "https://www.niyogkhoje.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "All Result BD", d: "রেজাল্ট ও চাকরি", url: "https://www.allresultbd.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Teletalk Job", d: "টেলিটক চাকরি", url: "https://www.teletalk.com.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "PSC Teletalk", d: "পিএসসি ফর্ম", url: "https://psc.teletalk.com.bd", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Mofa Job", d: "পররাষ্ট্র মন্ত্রণালয়", url: "https://mofa.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Army Job", d: "সেনাবাহিনী চাকরি", url: "https://join.army.mil.bd", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Navy Job", d: "নৌবাহিনী চাকরি", url: "https://www.navy.mil.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Air Force Job", d: "বিমান বাহিনী চাকরি", url: "https://baf.mil.bd", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Police Job", d: "পুলিশ চাকরি", url: "https://www.police.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "BGB Job", d: "বিজিবি চাকরি", url: "https://bgb.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Ansar VDP", d: "আনসার ভিডিপি", url: "https://ansarvdp.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Fire Service", d: "ফায়ার সার্ভিস", url: "https://fireservice.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "BRTA Job", d: "বিআরটিএ চাকরি", url: "https://brta.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "NBR Job", d: "এনবিআর চাকরি", url: "https://nbr.gov.bd/jobs", type: "govt" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Bank Job BD", d: "ব্যাংক চাকরি", url: "https://www.bankjobbangladesh.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "Teaching Job", d: "শিক্ষক চাকরি", url: "https://www.teachingbd.com", type: "private" },
    { cat: "চাকরি", icon: "fa-briefcase", t: "NGO Job", d: "এনজিও চাকরি", url: "https://www.ngojobsite.com", type: "private" },

    // ==================== ফ্রিল্যান্সিং ====================
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Upwork", d: "ফ্রিল্যান্সিং মার্কেটপ্লেস", url: "https://www.upwork.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Fiverr", d: "ফ্রিল্যান্সিং মার্কেটপ্লেস", url: "https://www.fiverr.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Freelancer", d: "ফ্রিল্যান্সিং মার্কেটপ্লেস", url: "https://www.freelancer.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Guru", d: "ফ্রিল্যান্সিং", url: "https://www.guru.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "PeoplePerHour", d: "ফ্রিল্যান্সিং", url: "https://www.peopleperhour.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Toptal", d: "প্রফেশনাল ফ্রিল্যান্সিং", url: "https://www.toptal.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "99designs", d: "ডিজাইন ফ্রিল্যান্সিং", url: "https://99designs.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Dribbble", d: "ডিজাইনার পোর্টফোলিও", url: "https://dribbble.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Behance", d: "ডিজাইনার পোর্টফোলিও", url: "https://www.behance.net", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Envato Market", d: "ডিজিটাল অ্যাসেট", url: "https://themeforest.net", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Shutterstock", d: "স্টক ইমেজ বিক্রি", url: "https://www.shutterstock.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "iStock", d: "স্টক ইমেজ বিক্রি", url: "https://www.istockphoto.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Teepublic", d: "টি-শার্ট ডিজাইন", url: "https://www.teepublic.com", type: "private" },
    { cat: "ফ্রিল্যান্সিং", icon: "fa-laptop-house", t: "Redbubble", d: "প্রিন্ট অন ডিমান্ড", url: "https://www.redbubble.com", type: "private" },

    // ==================== বিনোদন ====================
    { cat: "বিনোদন", icon: "fa-music", t: "Spotify", d: "মিউজিক স্ট্রিমিং", url: "https://www.spotify.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-music", t: "Saavn", d: "ইন্ডিয়ান মিউজিক", url: "https://www.jiosaavn.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-music", t: "Gaana", d: "মিউজিক স্ট্রিমিং", url: "https://gaana.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Netflix", d: "মুভি স্ট্রিমিং", url: "https://www.netflix.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Amazon Prime", d: "মুভি স্ট্রিমিং", url: "https://www.primevideo.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Disney+ Hotstar", d: "মুভি স্ট্রিমিং", url: "https://www.hotstar.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Hulu", d: "মুভি স্ট্রিমিং", url: "https://www.hulu.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Bongo BD", d: "বাংলা মুভি", url: "https://www.bongobd.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Bioscope", d: "বাংলা কন্টেন্ট", url: "https://bioscopelive.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Hoichoi", d: "বাংলা মুভি", url: "https://www.hoichoi.tv", type: "private" },
    { cat: "বিনোদন", icon: "fa-film", t: "Zee5", d: "মুভি স্ট্রিমিং", url: "https://www.zee5.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-gamepad", t: "PUBG Mobile", d: "মোবাইল গেম", url: "https://www.pubgmobile.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-gamepad", t: "Free Fire", d: "মোবাইল গেম", url: "https://ff.garena.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-gamepad", t: "Call of Duty Mobile", d: "মোবাইল গেম", url: "https://www.callofduty.com/mobile", type: "private" },
    { cat: "বিনোদন", icon: "fa-gamepad", t: "Steam", d: "পিসি গেম", url: "https://store.steampowered.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-gamepad", t: "Epic Games", d: "পিসি গেম", url: "https://www.epicgames.com", type: "private" },
    { cat: "বিনোদন", icon: "fa-twitch", t: "Twitch", d: "গেম স্ট্রিমিং", url: "https://www.twitch.tv", type: "private" },
    { cat: "বিনোদন", icon: "fa-youtube", t: "YouTube Gaming", d: "গেম ভিডিও", url: "https://www.youtube.com/gaming", type: "private" },

    // ==================== ট্যুরিজম ও ভ্রমণ ====================
    { cat: "ভ্রমণ", icon: "fa-umbrella-beach", t: "Cox's Bazar", d: "ট্যুরিজম তথ্য", url: "https://www.coxsbazar.gov.bd", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-mountain", t: "Bandarban", d: "পর্যটন তথ্য", url: "https://www.bandarban.gov.bd", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-tree", t: "Sundarban", d: "সুন্দরবন তথ্য", url: "https://www.sundarban.gov.bd", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-water", t: "Sylhet Tourism", d: "সিলেট পর্যটন", url: "https://www.sylhet.gov.bd", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-landmark", t: "Bangladesh Tourism Board", d: "পর্যটন বোর্ড", url: "https://www.tourismboard.gov.bd", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-plane", t: "Biman Bangladesh", d: "ফ্লাইট বুকিং", url: "https://www.biman-airlines.com", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-plane", t: "US-Bangla", d: "ফ্লাইট বুকিং", url: "https://usbair.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-plane", t: "NovoAir", d: "ফ্লাইট বুকিং", url: "https://www.flynovoair.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-plane", t: "Air Astra", d: "ফ্লাইট বুকিং", url: "https://airastra.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-train", t: "Railway", d: "ট্রেনের টিকেট", url: "https://eticket.railway.gov.bd", type: "govt" },
    { cat: "ভ্রমণ", icon: "fa-bus", t: "Shohoz", d: "বাস/লঞ্চ টিকেট", url: "https://www.shohoz.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-bus", t: "Busbd", d: "বাস টিকেট", url: "https://www.busbd.com.bd", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-hotel", t: "Booking.com", d: "হোটেল বুকিং", url: "https://www.booking.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-hotel", t: "Agoda", d: "হোটেল বুকিং", url: "https://www.agoda.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-hotel", t: "Airbnb", d: "হোম স্টে", url: "https://www.airbnb.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-hotel", t: "Travelocity", d: "ভ্রমণ বুকিং", url: "https://www.travelocity.com", type: "private" },
    { cat: "ভ্রমণ", icon: "fa-hotel", t: "Expedia", d: "ভ্রমণ বুকিং", url: "https://www.expedia.com", type: "private" },

    // ==================== খেলাধুলা ====================
    { cat: "খেলাধুলা", icon: "fa-cricket", t: "Tiger Cricket", d: "বিসিবি", url: "https://www.tigercricket.com.bd", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-futbol", t: "BFF", d: "বাংলাদেশ ফুটবল", url: "https://www.bff.com.bd", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-futbol", t: "Bashundhara Kings", d: "ফুটবল ক্লাব", url: "https://www.bashundharakings.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-futbol", t: "Abahani Limited", d: "ফুটবল ক্লাব", url: "https://www.abahaniltd.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-cricket", t: "BCB", d: "বাংলাদেশ ক্রিকেট", url: "https://www.tigercricket.com.bd", type: "govt" },
    { cat: "খেলাধুলা", icon: "fa-running", t: "BOA", d: "বাংলাদেশ অলিম্পিক", url: "https://www.nocbd.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-cricket", t: "ESPN Cricinfo", d: "ক্রিকেট খবর", url: "https://www.espncricinfo.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-futbol", t: "FIFA", d: "ফিফা ওয়েবসাইট", url: "https://www.fifa.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-futbol", t: "UEFA", d: "উয়েফা ওয়েবসাইট", url: "https://www.uefa.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-cricket", t: "ICC", d: "আন্তর্জাতিক ক্রিকেট", url: "https://www.icc-cricket.com", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-cricket", t: "BCB TV", d: "বিসিবি টিভি", url: "https://www.youtube.com/@BCBTV", type: "private" },
    { cat: "খেলাধুলা", icon: "fa-cricket", t: "Rabbithole", d: "স্পোর্টস স্ট্রিমিং", url: "https://rabbitholebd.com", type: "private" },

    // ==================== অন্যান্য গুরুত্বপূর্ণ ====================
    { cat: "অন্যান্য", icon: "fa-globe", t: "Wikipedia", d: "অনলাইন বিশ্বকোষ", url: "https://www.wikipedia.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Banglapedia", d: "বাংলাদেশ বিশ্বকোষ", url: "https://bn.banglapedia.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Amazon", d: "অনলাইন শপিং", url: "https://www.amazon.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "AliExpress", d: "চায়না শপিং", url: "https://www.aliexpress.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "eBay", d: "অনলাইন নিলাম", url: "https://www.ebay.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Payoneer", d: "পেমেন্ট সেবা", url: "https://www.payoneer.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "PayPal", d: "পেমেন্ট সেবা", url: "https://www.paypal.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Wise", d: "টাকা ট্রান্সফার", url: "https://wise.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Skrill", d: "পেমেন্ট সেবা", url: "https://www.skrill.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Neteller", d: "পেমেন্ট সেবা", url: "https://www.neteller.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Western Union", d: "টাকা ট্রান্সফার", url: "https://www.westernunion.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "MoneyGram", d: "টাকা ট্রান্সফার", url: "https://www.moneygram.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Xoom", d: "পেপাল ট্রান্সফার", url: "https://www.xoom.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "WorldRemit", d: "টাকা ট্রান্সফার", url: "https://www.worldremit.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Remitly", d: "টাকা ট্রান্সফার", url: "https://www.remitly.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Taptap Send", d: "টাকা ট্রান্সফার", url: "https://www.taptapsend.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DHL", d: "কুরিয়ার সেবা", url: "https://www.dhl.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "FedEx", d: "কুরিয়ার সেবা", url: "https://www.fedex.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UPS", d: "কুরিয়ার সেবা", url: "https://www.ups.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Sundarban Courier", d: "লোকাল কুরিয়ার", url: "https://www.sundarbancourier.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SA Paribahan", d: "লোকাল কুরিয়ার", url: "https://www.saparibahan.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Paperfly", d: "ই-কমার্স ডেলিভারি", url: "https://www.paperfly.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "RedX", d: "ই-কমার্স ডেলিভারি", url: "https://www.redx.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Steadfast", d: "ই-কমার্স ডেলিভারি", url: "https://steadfast.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Pathao Courier", d: "কুরিয়ার সেবা", url: "https://pathao.com/courier", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "eCourier", d: "কুরিয়ার সেবা", url: "https://ecourier.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Rapid Pass", d: "অ্যাপ", url: "https://rapidpass.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Surokkha", d: "ভ্যাকসিন অ্যাপ", url: "https://surokkha.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BDApps", d: "মোবাইল অ্যাপ", url: "https://bdapps.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "GP App", d: "গ্রামীণফোন অ্যাপ", url: "https://www.grameenphone.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Robi", d: "রবি অ্যাপ", url: "https://www.robi.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Banglalink", d: "বাংলালিংক অ্যাপ", url: "https://www.banglalink.net", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Teletalk", d: "টেলিটক", url: "https://www.teletalk.com.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Skitto", d: "জিপি স্কিটো", url: "https://www.skitto.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Airtel", d: "এয়ারটেল", url: "https://www.airtel.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BTCL", d: "বিটিসিএল", url: "https://www.btcl.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BTRC", d: "টেলিকম নিয়ন্ত্রক", url: "https://www.btrc.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "LiveScore", d: "স্পোর্টস স্কোর", url: "https://www.livescore.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Goal.com", d: "ফুটবল নিউজ", url: "https://www.goal.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Transfermarkt", d: "ফুটবল ট্রান্সফার", url: "https://www.transfermarkt.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Duolingo", d: "ভাষা শেখা", url: "https://www.duolingo.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Khan Academy", d: "ফ্রি শিক্ষা", url: "https://www.khanacademy.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "TED", d: "অনুপ্রেরণামূলক বক্তৃতা", url: "https://www.ted.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Medium", d: "ব্লগ প্ল্যাটফর্ম", url: "https://medium.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "WordPress", d: "ব্লগ ও ওয়েবসাইট", url: "https://wordpress.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Blogger", d: "গুগল ব্লগ", url: "https://www.blogger.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Figma", d: "ডিজাইন টুল", url: "https://www.figma.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Trello", d: "প্রজেক্ট ম্যানেজমেন্ট", url: "https://trello.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Asana", d: "প্রজেক্ট ম্যানেজমেন্ট", url: "https://asana.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Slack", d: "টিম কমিউনিকেশন", url: "https://slack.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Discord", d: "কমিউনিটি চ্যাট", url: "https://discord.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Notion", d: "নোট টেকিং", url: "https://www.notion.so", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Evernote", d: "নোট টেকিং", url: "https://evernote.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Grammarly", d: "ইংরেজি গ্রামার চেক", url: "https://www.grammarly.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "QuillBot", d: "প্যারাফ্রেজিং টুল", url: "https://quillbot.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Remove.bg", d: "ব্যাকগ্রাউন্ড রিমুভ", url: "https://www.remove.bg", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "TinyPNG", d: "ইমেজ কম্প্রেস", url: "https://tinypng.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ILovePDF", d: "পিডিএফ টুলস", url: "https://www.ilovepdf.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Down for Everyone", d: "ওয়েবসাইট চেক", url: "https://downforeveryoneorjustme.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Speedtest", d: "ইন্টারনেট স্পিড", url: "https://www.speedtest.net", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Fast.com", d: "নেটফ্লিক্স স্পিড", url: "https://fast.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "WhatIsMyIP", d: "আইপি এড্রেস", url: "https://www.whatismyip.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "VirusTotal", d: "ফাইল ভাইরাস চেক", url: "https://www.virustotal.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Have I Been Pwned", d: "ইমেইল লিক চেক", url: "https://haveibeenpwned.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "10 Minute Mail", d: "টেম্পোরারি ইমেইল", url: "https://10minutemail.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Temp Mail", d: "টেম্পোরারি ইমেইল", url: "https://temp-mail.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Receive SMS", d: "ভার্চুয়াল নম্বর", url: "https://receive-smss.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Translate", d: "অনুবাদ", url: "https://translate.google.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DeepL", d: "অনুবাদ", url: "https://www.deepl.com/translator", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ChatGPT", d: "এআই চ্যাট", url: "https://chat.openai.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Gemini", d: "গুগল এআই", url: "https://gemini.google.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Claude", d: "এআই চ্যাট", url: "https://claude.ai", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Midjourney", d: "এআই ইমেজ", url: "https://www.midjourney.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DALL-E", d: "এআই ইমেজ", url: "https://openai.com/dall-e-3", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Leonardo AI", d: "এআই ইমেজ", url: "https://leonardo.ai", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Suno AI", d: "এআই মিউজিক", url: "https://suno.ai", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Runway ML", d: "এআই ভিডিও", url: "https://runwayml.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Pexels", d: "ফ্রি স্টক ইমেজ", url: "https://www.pexels.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Unsplash", d: "ফ্রি স্টক ইমেজ", url: "https://unsplash.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Pixabay", d: "ফ্রি স্টক ইমেজ", url: "https://pixabay.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Mixkit", d: "ফ্রি ভিডিও", url: "https://mixkit.co", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Coverr", d: "ফ্রি ভিডিও", url: "https://coverr.co", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Freesound", d: "ফ্রি সাউন্ড", url: "https://freesound.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Zapsplat", d: "ফ্রি সাউন্ড", url: "https://www.zapsplat.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Font Awesome", d: "আইকন লাইব্রেরি", url: "https://fontawesome.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Fonts", d: "ফ্রি ফন্ট", url: "https://fonts.google.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Flaticon", d: "ফ্রি আইকন", url: "https://www.flaticon.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Icons8", d: "ফ্রি আইকন", url: "https://icons8.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "CDNJS", d: "ফ্রি CDN", url: "https://cdnjs.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "JsDelivr", d: "ফ্রি CDN", url: "https://www.jsdelivr.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Unpkg", d: "ফ্রি CDN", url: "https://unpkg.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "CodePen", d: "কোড প্লেগ্রাউন্ড", url: "https://codepen.io", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "JSFiddle", d: "কোড প্লেগ্রাউন্ড", url: "https://jsfiddle.net", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Replit", d: "অনলাইন কোডিং", url: "https://replit.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Glitch", d: "অনলাইন কোডিং", url: "https://glitch.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "StackBlitz", d: "অনলাইন কোডিং", url: "https://stackblitz.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Postman", d: "API টেস্টিং", url: "https://www.postman.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Insomnia", d: "API টেস্টিং", url: "https://insomnia.rest", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "JSONPlaceholder", d: "ফেক API", url: "https://jsonplaceholder.typicode.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Reqres", d: "ফেক API", url: "https://reqres.in", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DummyJSON", d: "ফেক API", url: "https://dummyjson.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Cron-job.org", d: "ফ্রি ক্রোন জব", url: "https://cron-job.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UptimeRobot", d: "ওয়েবসাইট মনিটর", url: "https://uptimerobot.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Freshping", d: "ফ্রি মনিটরিং", url: "https://www.freshworks.com/website-monitoring/", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Disqus", d: "কমেন্ট সিস্টেম", url: "https://disqus.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Mailchimp", d: "ইমেইল মার্কেটিং", url: "https://mailchimp.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SendGrid", d: "ইমেইল API", url: "https://sendgrid.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Twilio", d: "এসএমএস API", url: "https://www.twilio.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Stripe", d: "পেমেন্ট গেটওয়ে", url: "https://stripe.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SSLCommerz", d: "বাংলাদেশী পেমেন্ট", url: "https://www.sslcommerz.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ShurjoPay", d: "বাংলাদেশী পেমেন্ট", url: "https://shurjopay.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "aamarPay", d: "বাংলাদেশী পেমেন্ট", url: "https://aamarpay.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "PortWallet", d: "বাংলাদেশী পেমেন্ট", url: "https://www.portwallet.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Namecheap", d: "ডোমেইন রেজিস্ট্রার", url: "https://www.namecheap.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "GoDaddy", d: "ডোমেইন রেজিস্ট্রার", url: "https://www.godaddy.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Cloudflare", d: "CDN ও DNS", url: "https://www.cloudflare.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Let's Encrypt", d: "ফ্রি SSL", url: "https://letsencrypt.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ZeroSSL", d: "ফ্রি SSL", url: "https://zerossl.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "GTmetrix", d: "ওয়েবসাইট স্পিড", url: "https://gtmetrix.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "PageSpeed Insights", d: "গুগল স্পিড টেস্ট", url: "https://pagespeed.web.dev", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Pingdom", d: "ওয়েবসাইট স্পিড", url: "https://tools.pingdom.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Can I Use", d: "ব্রাউজার সাপোর্ট", url: "https://caniuse.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Wappalyzer", d: "ওয়েবসাইট টেক", url: "https://www.wappalyzer.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BuiltWith", d: "ওয়েবসাইট টেক", url: "https://builtwith.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SimilarWeb", d: "ওয়েবসাইট অ্যানালিটিক্স", url: "https://www.similarweb.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Ahrefs", d: "SEO টুল", url: "https://ahrefs.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SEMrush", d: "SEO টুল", url: "https://www.semrush.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Moz", d: "SEO টুল", url: "https://moz.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Yoast SEO", d: "ওয়ার্ডপ্রেস SEO", url: "https://yoast.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Analytics", d: "ওয়েব অ্যানালিটিক্স", url: "https://analytics.google.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Search Console", d: "সার্চ কনসোল", url: "https://search.google.com/search-console", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Tag Manager", d: "ট্যাগ ম্যানেজার", url: "https://tagmanager.google.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Hotjar", d: "হিটম্যাপ ও রেকর্ডিং", url: "https://www.hotjar.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Microsoft Clarity", d: "ফ্রি হিটম্যাপ", url: "https://clarity.microsoft.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SurveyMonkey", d: "অনলাইন সার্ভে", url: "https://www.surveymonkey.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Forms", d: "ফ্রি ফর্ম", url: "https://forms.google.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Typeform", d: "অনলাইন ফর্ম", url: "https://www.typeform.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "JotForm", d: "অনলাইন ফর্ম", url: "https://www.jotform.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Calendly", d: "অ্যাপয়েন্টমেন্ট", url: "https://calendly.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Doodle", d: "মিটিং পোল", url: "https://doodle.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "LastPass", d: "পাসওয়ার্ড ম্যানেজার", url: "https://www.lastpass.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bitwarden", d: "ওপেন সোর্স পাসওয়ার্ড", url: "https://bitwarden.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "1Password", d: "পাসওয়ার্ড ম্যানেজার", url: "https://1password.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Proton Mail", d: "সিকিউর ইমেইল", url: "https://proton.me/mail", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Proton VPN", d: "ফ্রি ভিপিএন", url: "https://protonvpn.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Proton Drive", d: "সিকিউর ক্লাউড", url: "https://proton.me/drive", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "NordVPN", d: "ভিপিএন", url: "https://nordvpn.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ExpressVPN", d: "ভিপিএন", url: "https://www.expressvpn.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Archive.org", d: "ওয়েব আর্কাইভ", url: "https://archive.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Wayback Machine", d: "ওয়েব আর্কাইভ", url: "https://web.archive.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Time.is", d: "সঠিক সময়", url: "https://time.is", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "World Time Buddy", d: "টাইম জোন কনভার্টার", url: "https://www.worldtimebuddy.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Timezone Converter", d: "টাইম জোন", url: "https://www.timezoneconverter.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Unit Converters", d: "ইউনিট কনভার্টার", url: "https://www.unitconverters.net", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "XE Currency", d: "কারেন্সি কনভার্টার", url: "https://www.xe.com/currencyconverter/", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Currency", d: "কারেন্সি কনভার্টার", url: "https://www.google.com/finance/converter", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "OANDA", d: "কারেন্সি কনভার্টার", url: "https://www.oanda.com/currency-converter", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Exchange Rates", d: "এক্সচেঞ্জ রেট", url: "https://www.exchangerates.org.uk", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IMF Data", d: "আইএমএফ ডেটা", url: "https://data.imf.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "World Bank Data", d: "বিশ্বব্যাংক ডেটা", url: "https://data.worldbank.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Trading Economics", d: "ইকোনমিক ডেটা", url: "https://tradingeconomics.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Investopedia", d: "ফাইন্যান্স শেখা", url: "https://www.investopedia.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Yahoo Finance", d: "স্টক মার্কেট", url: "https://finance.yahoo.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Google Finance", d: "স্টক মার্কেট", url: "https://www.google.com/finance", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "TradingView", d: "স্টক চার্ট", url: "https://www.tradingview.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Binance", d: "ক্রিপ্টো এক্সচেঞ্জ", url: "https://www.binance.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "CoinMarketCap", d: "ক্রিপ্টো মার্কেট", url: "https://coinmarketcap.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "CoinGecko", d: "ক্রিপ্টো মার্কেট", url: "https://www.coingecko.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DSE", d: "ঢাকা স্টক এক্সচেঞ্জ", url: "https://www.dsebd.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "CSE", d: "চট্টগ্রাম স্টক এক্সচেঞ্জ", url: "https://www.cse.com.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Stock Bangladesh", d: "বাংলাদেশ স্টক", url: "https://www.stockbangladesh.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IDLC", d: "ফাইন্যান্স কোম্পানি", url: "https://www.idlc.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "LankaBangla", d: "ফাইন্যান্স কোম্পানি", url: "https://www.lankabangla.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IFIC Bank", d: "ইন্টারন্যাশনাল ফাইন্যান্স", url: "https://www.ificbank.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Uttara Finance", d: "ফাইন্যান্স কোম্পানি", url: "https://www.uttarafinance.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BD Finance", d: "ফাইন্যান্স কোম্পানি", url: "https://www.bdfinance.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IPDC", d: "ফাইন্যান্স কোম্পানি", url: "https://www.ipdcbd.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Grameen Bank", d: "গ্রামীণ ব্যাংক", url: "https://www.grameenbank.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BRAC Microfinance", d: "ব্র্যাক মাইক্রোফাইন্যান্স", url: "https://www.brac.net/microfinance", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ASA Bangladesh", d: "এএসএ মাইক্রোফাইন্যান্স", url: "https://www.asa.org.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BURO Bangladesh", d: "মাইক্রোফাইন্যান্স", url: "https://www.burobd.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "TMSS", d: "মাইক্রোফাইন্যান্স", url: "https://www.tmss-bd.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Shakti Foundation", d: "মাইক্রোফাইন্যান্স", url: "https://www.sfdw.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Jagorani Chakra", d: "মাইক্রোফাইন্যান্স", url: "https://www.jcf.org.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bangladesh Krishi Bank", d: "কৃষি ব্যাংক", url: "https://www.krishibank.org.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Rajshahi Krishi Unnayan Bank", d: "রাজশাহী কৃষি ব্যাংক", url: "https://www.rakub.org.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Probashi Kallyan Bank", d: "প্রবাসী কল্যাণ ব্যাংক", url: "https://www.pkb.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Palli Sanchay Bank", d: "পল্লী সঞ্চয় ব্যাংক", url: "https://www.pallisanchaybank.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Karmasangsthan Bank", d: "কর্মসংস্থান ব্যাংক", url: "https://www.karmasangsthanbank.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Ansar VDP Bank", d: "আনসার ভিডিপি ব্যাংক", url: "https://www.ansarvdpbank.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bangladesh Development Bank", d: "উন্নয়ন ব্যাংক", url: "https://www.bdbl.com.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BASIC Bank", d: "বেসিক ব্যাংক", url: "https://www.basicbanklimited.com", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "PKSF", d: "পল্লী কর্ম সহায়ক ফাউন্ডেশন", url: "https://www.pksf-bd.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Probashi Kallyan Board", d: "প্রবাসী কল্যাণ বোর্ড", url: "https://www.probashikallyan.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BMET", d: "জনশক্তি কর্মসংস্থান", url: "https://www.bmet.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BOESL", d: "ওভারসিজ এমপ্লয়মেন্ট", url: "https://www.boesl.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Expatrio", d: "জার্মানি ভিসা হেল্প", url: "https://www.expatrio.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DAAD Bangladesh", d: "জার্মানি স্কলারশিপ", url: "https://www.daad-bangladesh.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "British Council BD", d: "ব্রিটিশ কাউন্সিল", url: "https://www.britishcouncil.org.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IELTS", d: "আইইএলটিএস তথ্য", url: "https://www.ielts.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IDP IELTS BD", d: "আইইএলটিএস রেজিস্ট্রেশন", url: "https://www.idp.com/bangladesh/ielts", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "British Council IELTS", d: "আইইএলটিএস রেজিস্ট্রেশন", url: "https://www.britishcouncil.org.bd/en/exam/ielts", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "TOEFL", d: "টোফেল তথ্য", url: "https://www.ets.org/toefl", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "GRE", d: "জিআরই তথ্য", url: "https://www.ets.org/gre", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "GMAT", d: "জিম্যাট তথ্য", url: "https://www.mba.com/exams/gmat", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "SAT", d: "স্যাট তথ্য", url: "https://satsuite.collegeboard.org/sat", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Common App", d: "কলেজ অ্যাপ্লিকেশন", url: "https://www.commonapp.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UCAS", d: "ইউকে ইউনিভার্সিটি", url: "https://www.ucas.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ApplyBoard", d: "কানাডা স্টাডি", url: "https://www.applyboard.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IDP Study Abroad", d: "বিদেশে পড়াশোনা", url: "https://www.idp.com/bangladesh/study-abroad", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "KC Overseas BD", d: "বিদেশে পড়াশোনা", url: "https://www.studies-overseas.com/bangladesh", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Global Study BD", d: "বিদেশে পড়াশোনা", url: "https://www.globalstudy.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Scholarship Corner", d: "স্কলারশিপ তথ্য", url: "https://www.scholarshipcorner.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Scholars4Dev", d: "স্কলারশিপ তথ্য", url: "https://www.scholars4dev.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Opportunity Desk", d: "স্কলারশিপ তথ্য", url: "https://opportunitydesk.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Youth Opportunities", d: "ইয়ুথ অপরচুনিটি", url: "https://www.youthop.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bdjobs Training", d: "প্রশিক্ষণ কোর্স", url: "https://www.bdjobs.com/training", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "LEDP", d: "লার্নিং অ্যান্ড আর্নিং", url: "https://www.ledp.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ICT Division", d: "তথ্য প্রযুক্তি বিভাগ", url: "https://ictd.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "A2I", d: "অ্যাকসেস টু ইনফরমেশন", url: "https://a2i.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BCC", d: "বাংলাদেশ কম্পিউটার কাউন্সিল", url: "https://www.bcc.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BASIS", d: "সফটওয়্যার অ্যাসোসিয়েশন", url: "https://www.basis.org.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BACCO", d: "কল সেন্টার অ্যাসোসিয়েশন", url: "https://www.bacco.org.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "E-CAB", d: "ই-কমার্স অ্যাসোসিয়েশন", url: "https://www.e-cab.net", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bangladesh Association of Banks", d: "ব্যাংক অ্যাসোসিয়েশন", url: "https://www.bab-bd.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "MCCI", d: "মেট্রোপলিটন চেম্বার", url: "https://www.mccibd.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "DCCI", d: "ঢাকা চেম্বার", url: "https://www.dhakachamber.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "FBCCI", d: "ব্যবসায়ী ফেডারেশন", url: "https://www.fbcci.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BGMEA", d: "গার্মেন্টস অ্যাসোসিয়েশন", url: "https://www.bgmea.com.bd", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BKMEA", d: "নিটওয়্যার অ্যাসোসিয়েশন", url: "https://www.bkmea.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BTMA", d: "টেক্সটাইল অ্যাসোসিয়েশন", url: "https://www.btmadhaka.com", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BEPZA", d: "রপ্তানি প্রক্রিয়াকরণ", url: "https://www.bepza.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BEZA", d: "অর্থনৈতিক অঞ্চল", url: "https://www.beza.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BIDA", d: "বিনিয়োগ উন্নয়ন কর্তৃপক্ষ", url: "https://www.bida.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BSEC", d: "সিকিউরিটিজ কমিশন", url: "https://www.sec.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IDRA", d: "বীমা উন্নয়ন কর্তৃপক্ষ", url: "https://www.idra.org.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "MRA", d: "মাইক্রোক্রেডিট কর্তৃপক্ষ", url: "https://www.mra.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "RAJUK", d: "রাজধানী উন্নয়ন কর্তৃপক্ষ", url: "https://www.rajukdhaka.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "CMP", d: "চট্টগ্রাম মেট্রোপলিটন", url: "https://www.cmp.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "KDA", d: "খুলনা উন্নয়ন কর্তৃপক্ষ", url: "https://www.kda.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "RDA", d: "রাজশাহী উন্নয়ন কর্তৃপক্ষ", url: "https://www.rda.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "NHA", d: "জাতীয় গৃহায়ন কর্তৃপক্ষ", url: "https://www.nha.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "HBRI", d: "গৃহায়ন ও ভবন গবেষণা", url: "https://www.hbri.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BSCIC", d: "ক্ষুদ্র ও কুটির শিল্প", url: "https://www.bscic.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BBS", d: "পরিসংখ্যান ব্যুরো", url: "https://www.bbs.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IMED", d: "পরিকল্পনা মন্ত্রণালয়", url: "https://www.imed.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Planning Commission", d: "পরিকল্পনা কমিশন", url: "https://www.plancomm.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Finance Division", d: "অর্থ বিভাগ", url: "https://www.mof.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IRD", d: "অভ্যন্তরীণ সম্পদ বিভাগ", url: "https://www.ird.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Customs", d: "কাস্টমস", url: "https://www.customs.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "VAT Online", d: "ভ্যাট অনলাইন", url: "https://www.vat.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bangladesh Parliament", d: "জাতীয় সংসদ", url: "https://www.parliament.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Supreme Court", d: "সুপ্রিম কোর্ট", url: "https://www.supremecourt.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Law Ministry", d: "আইন মন্ত্রণালয়", url: "https://www.lawjusticediv.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Legislative Department", d: "লেজিসলেটিভ বিভাগ", url: "https://www.legislative.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Bangladesh Code", d: "বাংলাদেশ কোড", url: "https://bdlaws.minlaw.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "BIDA One Stop", d: "ওয়ান স্টপ সার্ভিস", url: "https://www.oss.bida.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "MyGov BD", d: "মাইগভ", url: "https://www.mygov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "EkShop", d: "গ্রামীণ ই-কমার্স", url: "https://www.ekshop.gov.bd", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "TCT", d: "ট্রান্সপারেন্সি ইন্টারন্যাশনাল", url: "https://www.ti-bangladesh.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Human Rights Watch", d: "মানবাধিকার সংস্থা", url: "https://www.hrw.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Amnesty International", d: "অ্যামনেস্টি ইন্টারন্যাশনাল", url: "https://www.amnesty.org", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UN Bangladesh", d: "জাতিসংঘ বাংলাদেশ", url: "https://bangladesh.un.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UNDP Bangladesh", d: "ইউএনডিপি বাংলাদেশ", url: "https://www.undp.org/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "WHO Bangladesh", d: "বিশ্ব স্বাস্থ্য সংস্থা", url: "https://www.who.int/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UNICEF Bangladesh", d: "ইউনিসেফ বাংলাদেশ", url: "https://www.unicef.org/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ILO Bangladesh", d: "আন্তর্জাতিক শ্রম সংস্থা", url: "https://www.ilo.org/dhaka", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "World Bank Bangladesh", d: "বিশ্বব্যাংক বাংলাদেশ", url: "https://www.worldbank.org/en/country/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "ADB Bangladesh", d: "এশীয় উন্নয়ন ব্যাংক", url: "https://www.adb.org/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IMF Bangladesh", d: "আইএমএফ বাংলাদেশ", url: "https://www.imf.org/en/Countries/BGD", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "US Embassy BD", d: "যুক্তরাষ্ট্র দূতাবাস", url: "https://bd.usembassy.gov", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "UK in Bangladesh", d: "ব্রিটিশ হাইকমিশন", url: "https://www.gov.uk/world/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Canada in Bangladesh", d: "কানাডিয়ান হাইকমিশন", url: "https://www.international.gc.ca/country-pays/bangladesh", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Australia in Bangladesh", d: "অস্ট্রেলিয়ান হাইকমিশন", url: "https://bangladesh.embassy.gov.au", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "India in Bangladesh", d: "ভারতীয় হাইকমিশন", url: "https://www.hcidhaka.gov.in", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Japan in Bangladesh", d: "জাপানি দূতাবাস", url: "https://www.bd.emb-japan.go.jp", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "Saudi Embassy BD", d: "সৌদি দূতাবাস", url: "https://www.saudiembassydhaka.org", type: "govt" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "VFS Global BD", d: "ভিসা সেবা", url: "https://www.vfsglobal.com/bangladesh", type: "private" },
    { cat: "অন্যান্য", icon: "fa-globe", t: "IVAC BD", d: "ভারতীয় ভিসা", url: "https://www.ivacbd.com", type: "private" },
];

// প্রয়োজনে শেষে এই লাইনটি দিন যদি মডিউল হিসেবে ব্যবহার করতে চান
// module.exports = services;
      
